apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/istio/istio'
      #    targetRevision: HEAD
    targetRevision: f6d7bf648e571a6a523210d97bde8b489250354b # tag 1.16.1
    path: manifests/charts/istio-operator
    helm:
      parameters:
      - name: hub
        value: docker.io/istio
      - name: tag
#        value: 1.10.1 # istio/operator
        value: 1.14.6
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
