kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
  encryptedData:
    postgresql-password: AgCI88tVE2Ho3izUuC8LlgfrLX2a0c9kgmfYhEDgsz8aS6fpZbakb/giakCDh7HXgz23dTQm+Le2Gok6OwvkL0QmaxcL3BEquFbZQOvzG8SiGbSbLDKGi12OQ044EEPKyldFyQXdapmjwcpOZGIIp1bmKPbPy8hvBoF60wjc5ukshk7kvlDNcMd+50t6aLlsgWDj5KdpvwgTdwM8cDtNq1KA3fKybeyyzLjZKteQ/sgozU/UNgHawtyZb+WJcMfqTUld+ODkrCnbuEL+kwBFJJctAyGcZH8dyYU/LCKLTDfkGr5LW7JjICc02xiPPN4RUtguzeWecssP7XoG6QTebVEAjh8JDeENt2QahEDHURXluvgHaL3hpT6I+fasAIckCz6mtnOHuvmrKWRNI40gFW+lQLx+NXPO4W/LiAEdJEHVeJtRzpeh5wW5m081yupEB34/Gmnrfu3JX+GcC97F3v67S8CyZ9n3+6BcTi0fAKxm+MAmwSDXHr/GF2Uszk7gmJT8YHYl21lc0+O5N2jOXintFslxuatY1ZtVAkAssPmA0P5mN979ltM37lRQZFJfUlrExxUUnljEOyqt/H3KK6ahIHilNJL/wlffCkchXmR0EakGkjH+hGVvyb7hdUfMbWnCM0aobntdTH9WP8GsCzBbI6HnGF8Gfll6H2EEYPh6Yp2t60F8zVJ6huV9FYHk+BJETwJL3M2L7tECd/6SHAvlb/vSolZ6xcMrSZ97TMBZtA==
    postgresql-postgres-password: AgCFFFJRfg5H9ku5axsyQO+D6PZ5hlpMEaLeSJj30YFmf7qMFjJpAhy0xVE+XnznUH0jxCTU/s3BZblxj5DUEzwzr239qdMR8eHdRHP00b2rDG+n8gL5oOXGCCIrSgjbwOYcjFGtUcvq/UvTUqxcFKhNchB58UOwGx/7oTij/8SOM8zfgbWvMoQfKLkx+2CKer4MCDAkoGyZzKZ0e7S3l08AvAzxOq3PzUNEJt4fkqWygh8KSdSPoAR1cULLpXZXzV823yy5Ymhs+L9EdPivq/1U2bTG5rCy7utpIPvBCHpAWCdFUOrlDQgim//P+2szlwVA8xJsgeWlj+kV5U6jCNyy36nThIiAJCk/RkUnj9b7arUYuQhyZTckBM2UK/N9C8U42tApTSX7vWn2VH/JvWcqr49WiEucquwlFzdYbnuS2V+6EogVP1IoC5H7Tw/eeIOuCffvNmbSYHs0m12SBeK9Mu/BVLdNDFy+7wq3eR2CEgmD7Tkn5psNdDp/uCtB+1cZMW5kXHu+MfVV0GmhZoMPHa7FIun/xgr5mFlU2IzrNHU279BNcbJCdGLeYD0cyBmvNvat+WCKRTNg4SjBglEVcxBRYT1daLst478ZlhVXsyeSdPzf0hZ0qLbBQxMvbUs7UmBxox8QvBk/4UOLe2q/0/oJr8pBgk6PG95WF/6NClUEYF2uNIxw83W3hAOiCO2MX8PzF1FtfB3yVmRaPboQa/fTy8wQoeDmgu9XrGo4/w==
