kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
  encryptedData:
    postgresql-password: AgBqT46xfPjz/A7vJcu4iB0Vbpkb4ChNFiYxCBtRYSPjx4S8CDD8c1AewpAullHFmWu/j8zQUnefaNAqineiWk4MFnGnDhr8aryUsKL4ioZJaPohhZFBhDcW2t57jp3HVdkadY37XjatT3NQEStK1oddKr7yySKpYeij3G/bkdS/hHcWhHZsFZd4nKKwxtnEOzOX5zqUMFlwtedkY3EuQgPBm//fbX6f6hsISCfgHTHDDhNRwbiwpD5wgqI5azr1Ji0B1besVQ6GZ7LE2sj0q6jHiEt2dY9aANQKczGi9VvEnJEWMLBQZF2sRPKaeRlG2P5uVYnRkBUCdyoeKMJk9c8BUPnmByc7b44bg0ei5Tkdlsn/5NRpjXln0/97uPfpo0VLs0L4p8DhuHHuKUHBEcpza14CLljSAwELlU9zZAeGh6U++hwhh/WbgFsV/K67FngI9BxCW2ONGVslPoCm6Hhp2+LpCIzvDftqU3jPVX5zDa9JOD2m5u4s17kxXkIX6p7hXQWpb6MZf5AWmzd36E6FsXZuCDDXT/tjVpBrzmPDaipvR4bbHOubJ8W9jxh2koG6zGhH+74jazXIuTbUHQdbUsYm4qQg6Fh8wegKFONZfj7VhWdMvm8Q9nCvLybGPNHE875fxDQwFvVzZ6SvEcOtS0pm/KtNmDhyqM5Ui+xOC91nj5L/JwLYxqBaWPpDD3o0nytIrLpEGzN4ZDRdClHLHdY8YiJ0BMN/CvDpYtK/4A==
    postgresql-postgres-password: AgAYGld/Or+i/VIz9UjXic+DsUXaub69x+z9BICRsXrrTcBuMXP3JYFmKcXny8KkXuNpjoh2o2lOCG16JPjW9g2sb8Ztd7YRkPPBkJ5mLMhOb3LCaqa7THjMpppKTGBN/NccIDTNpH2FbGLkT/eH35JTxnxtDq73ij21NurbFW08al1ERg9P6P3Axv1hcrmZoZcJuPZaPgwUx4CwecIxLaGm5LETX0UKK0V3U0zRcNQBbco+rDm6K8tcaATt0a0lWGMmNRYXWsgucPKKLoCCmSByDMBZnkB1vSHXy015987CkCNZVUeOi5I1jiztF7rlwJrnZ+RCLjyRcU8cW8I1uW/KL8jMP3UVkaQiBAmh8XDeC20guHVDshdV72O+xmnPb+My2TCCoANx5C3wDoz8/+zZ6wivqonM8I8FpAAOR/R63SsQCdAvXjfjqniW+25X1dbYdFbf7soVblNqdLDgfoTude2Pgk3prcTs1DklpnaOKLTChCD9laDD4WDpz3PEePISQgr6AmfAdD4bajd+aJQyMLn6EzEHou3ZDXhsLz9HQeof1L1zp1I9mExLnaoDaGiOcf6pvFIh787EU+5xOtXSUkGr/cWu3IZPdPSMe3qX+bpSKkuL5dBzpguEMZcK74005jQGnVBtecyQ7On62+ihPddkY8mBDWvLpbE6X0eUyZKa30bEeT97WANtX4M7zZGRSEQr3deM5CGe0rw0zHuHot9Dv8SN3dCuN0NAHAzH7A==
