kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
  encryptedData:
    postgresql-password: AgAUjYUlJxdCt7wkg3+zI+OL6Ee0S3+J8xHIha60gx3u6iram1ya3RMqhjMXOFWQXTWdAhXJVoD98SpGiXm5FbqYqPe1Db3CskaMpjtAz9+AtV7bVg4Onr8/jvA64pr4LCKihO46n/tAm/Wt53uouvg/ZyleZbnxzIpCShrOLNIoOoT9611GjjgWVT7ElWrUhbIWm4DGPKu0MSNqStKXIb4xn2GZI73243sZvtCdVhfcrUPA2LK98vJ2YreYjhqlF9NQ3fppFg5eBn8fAJDrGrIJaPJyWTUmNkvCHJa8r1LBaf7vwDAzFaXCu+FvgnbO8LbRjlNqqLm1DZcKKoM+yvuAelhm3UNKHi157H2Xzb/CQ/eKHPpKzj8/ZH0ugc0dbAdwaX+4djsfXASlUl4xIq6BkFWKTy9cZsNn/KUNgEqY/C588qNtOIbgTOx8ugvPaffuMDy/ubShxvqeU52iOJzbMgkceZXQwak/Iig1pYUtGB82i44b+IYnZ5w50XneiE1mNWYF9EjgJiRQEhQJHFjS/EcmiCHlFIKFNCBoCaSSg1Mf8PRYVydJeLiXgWkJSXX4B6qUwQD82ubys/+3Tdne51yMdKpoJ+O3kMq2kY4/tMgbxhlvIUWGyMCmsaGnpAGMoFcqg9MptHaZxiTvfZXQAT+IluPwkzPDnZI45LmK47zBH6Whn+xSI91gRDVDkCgxRw70aVKqWH9w5isSnQ8e+498S6xM7Cf/mCbdjGMIjA==
    postgresql-postgres-password: AgB5bHh7NDGORoz+GmxD9DepgFxqSehHxq6w7HRCTW/weBs4O8imFKhGorhh8ktLL8Rarp4UGEfhxEqPUJa+DGFql7S6Ofrygj0T6/vecGqNZyIVPaFUP8C+jlrOj5O9+I0yRP2+JSctDAKvsQpSgBc+vVVJbMIvfp6HRZExbP3+8lvsY2Apm9DxuocD1GBoZoH/fsfZkNeK++OeseZ4CMiybfKRtIBiVQuqxq48Hl/jKHZwFm64qZOzH4n0DCRxbuN4mZ8AfToyCIUpjjF1uB2L4WtJtOpntgjWBNREI8yhW1fRFDDiP9poTu9ur9011E3hnPtUa9zV7A2+vBD/ZpfkqaYM4TylR/5nQk2ZTsaVns+SBhamHd88lEOHt1yz5dRtNbf+J1bbc/12YkEsXu38vN8VKh9FqS6GK5GDYSQyunN5FeoWbtCxpWExb268AViB9ZuxOpQ40drkX0yePH/2yWoLI4Oi8Sx4fRIpX6Bw1X2OinByMVDkNINXLHOqIy+I7v836eNBoECSRLtfz8BJ7H2pSYzkJyAm/ea6OjQHaqR2saOpVdSo09XR0SYeUU36PwQ9DrMW9HRcYaxD9eKzdp5Wx2fdFRfpcSNSJZdTj+IhGIHtIAKDtpa0n4XekwADPQog9GTwTHzDPRTcQaR+aEYjn7bFtnSMYf7puMtawgTKg+NfoXXTHrJI25FN67o+3Nh0MtiiAsrVbaWmIHJUEWji+Enhe9kVaA0bwe3JDw==
