kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgCIkyptHucNZPzL4rmAh5nVn93M1E2swNR2B15/UZIZwtXUm11ZYhzJYljszyQOsdJyCP/4//c30YrbHmVaq3IKRPczLfr9m36f750DFs5OWL0ETupGzssQgQjilIvei6IlnpnDtS58imbOJnVJJiK6/YHqfX2W9nPxcfldtM+hA5GVG3GoixboU8r0U98HoXrU1wkGVW/3b2jlpoGkJ87TPF4wgb9ycw6GcqbAfcn6dGSOp9hZg2czyidJYtZcyX+D1TA9Km6Uy0jXta5rb2mF2C9KgfWuc1PTde9ilmHko/JhIMT7ITPA2VT6IZhPOceF2yH8vsxJkFSaNYfBy0RBcqoPKBLq80lZov7m0Utd19HuB2d4jMF8jT80Ctmqa52hgayWPMR9O4WW8sq7+VDnxVkDqLec0cfqJkCdfoN1aPfAInTG3D17GnBuT5O5Ha+LAc3X+yCUP6rW29vUCvFnFna92bmSRnFMLEFr4x3vu8Ia2EYND5B9CSSUYQciqc58L2Q9BUNOBI9gyw3dFgbDvs1DQLKg6xdCGV6anFaJScA6jp5DVGFVcFRTh3tvSdJcwh13OfzA7cPQ6KPAU0Y8UkkvOoW0orlriJwzf8kCIb/S0VHHLsc3w5jWNmkP6HULhYwlVBcwD3LqfVMqB5wOt1MGUChZHHf7tR7mzrEP1ElzjJbPkbo7x3xY5o8681Pq4H/Ugg==
    admin-user: AgCTy+KLlvwNbYkjWggjAMukC4LMNlWOy/m6rqZreXBU+f5sIvdOhDI+vi8QgqJKD8/1RYpIAiUA+sO30tsU6UZkV4yPbRpSwpCPq7HfDGC9Gjo3LChmmdOxZhs0FQcYiuS/WLT+6hX6TNiFdRiuv0DTWYJSMnasLzV99HkjYJ3IwqPzhrZmWhe7vd+ZstUtomPQxJW9EgHNSFKlvLsNniny/OvMay8glPXeiucmYMXb370+tyIbbbunYB/9eKyZdx5QhcV1TZf5PCoIN2GnWcgACsCSK5Aor8B0MTAX9PN+rtNzYv+NLToSRatcpJQAAcwZEf22PWLKaQ5b4Lujl4QGOz/CXuXAhoYOBOYR9jpLnY7gKtrfFex3kRH8W27qEjYuAIIa/AgwSBSFS9otZrfOcyIY3xzIaI4uQIsbL+Rx66ijBhXHM5Ne2tQqiXBWtAj63vNw2J40h/CckKsiYq1ZyOyz3+IemdPGVImYZP6D7dh408dWHwjXIG6NAKjeovvf2kCE8DnFTVtm68/jN1U90Ey+jp+7PmZ72KUTyhr7FluLNFT4FYRJSehdz4Elm3EaJAQE33/n8v60XFKRDvgKYfwNDxYx9QMgJ+eedNVTiyladqvgh4monJS4/wO04ELrM/x1o7a0ErZe9Fl+mQ+Rla/Guz8LAG2J8IGvhG3SrxOH5HBuCDmgkoVGN+OwBgQtMpL2lA==
