kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgCc42SRMOgY4b9IqC4EwMo0W0tkzxIhYfV5jUulR0R0ws6XlK/MzVay4O/3bbQq9ePdIuwHnzLOAdZMxslo+MfagUS9SRxeI26ylL4uTGLRtyDiTwoiyWu9Mv0CWCk9FTWNHDk6HH3NWRlC3eaj8tTxy1cwWYRaJpkU+q0AFl9RALx1nS3JBL7uUrpVZUgXqlckW8A5h/NCHu2uKbCa9m923R7kzPzBWJsfb1O1KIj00N1XQfJu0M4hZClZ1tNF/+fcMtFDdPurnYf9NIOwZJxlikjCkJAfkMrUeWMYCz1UEZsR7H0fKeZ8m2yRh/M/+aWc1Gg7sDOzQwqRad1HF3az4KrK2jzFpyKxrIABspnwP0cQgl2Lfs9z7L1SONA0P+digPU7YI02BWkTdznJroLNmrYo7FrTNPP9MWKGJIvU593Zu3vYGWG30MgOV5qRihlno/+8Yz3/5sMWqzxK7LyxOVAxSvv+lPyV2Tzz7EJK+tQXi9xH6xfGM67ox74AL120rcyMtYD6RAoClb+lrMiFpD5SAoTYEXhCCTk8Uco9cJpoVSH8utbN3rTLUVeeJcUika1NMuOJlP9QSw83g0BCsojjcou2Sc+nmizLGWQzgp3rvF3muTJ4E2/v2Lavz9+q4c+uJMgACIYhRFq00bZcoUa6UM2aHFLkXNTi7ffcLomH//IRDEq6/cXd4SGvAD0snc7Ksg==
    admin-user: AgBVA3Skasdbah6iAy4mPHPg3yMv7iyVa1yX2IFl9LnKpzQRD3cQI0siU0rtT5VbLdLHkBfuJpWReTB0gYQNinVRt7EfBUuy2Skp6mApvr1V04wSQNOUIhyYo4IO9JQNrxAaIhnHRaGhO6cKqZ2sHZ90LgbXYhnPaVxquhbq3/2lbO+kFLQrrqzxwYj87jGq6wIZH/Kmee8JdSDablEm7vbfmXutXEK4nE6DZatrq1HW8AiTeR7kqYckoTv7d14Mk8eg5cJknqceI8lo5FyBxYxGm65kWlvmhAIKPkpOCuM66PUF3Z6hAXO+qVLPZQTo3A6qNNiwPf2yZPkzxnnxLSX0ICJi2OzvkvVPsikFsR5iStAF3GipMAd7t3aAovZsL05Ah6fSlU2+2aEAOZIjta5hDrS3xKbC+V3pCkTRw1qhK1rmvjC0a9tHnHF9bNjmDmAYef3C/MEBSyITI5ezJmykEko7a9dWd6n8BMhR0c0JybW382u3BgZ+4VTjmcgkGDDgbaQigAMFMfw9i6ILdz35Xsy13bLsTDD9aGbnhOELPCs1wATWl4YR1yMp4tpUePMTpHT1wyOpO2bIZd4IMwbMULWTmzkjLf6ZRQhFeOfHaTUyaOPUdBJ9CT4EChEE/ptIjWUhFsuq+Oh8cvNJKrOFOb9oV10GmHzOu1m4z5O5SMRWBBh9wQiKPCSG2msrzqS48DCQtA==
