kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgCZDLJQteeCqxixNL+qXwRyvMBTggY6GadG1ZRJKSqg2BwIBzwmGh5M50NC+os0ueN3LOGPHRHgSVui0yKRJqCgdes8QIJ96f9bKdbsT8PJ8wcI/r77+4l56XdTEjWqdNf6mlJiHXfiOKY6NALWlKBkw7/hh7mbt40OFNmzW2ZyTM+p/sIOdz+EWln62Cykpw3UyWI7Libbs5kHrcfEGdIvO3wk+CD4sKk5rqS7f1LovSoZJ+e3qf1iMEyflbQK8cxcoY/Pryy2gqNKrTu/olU8y/zNX5vxKVD3UYgAwDz+/EQdYi/B7V32ttXtY+iEtC+fIby1oT5tggbEt9Oi+nAhajQwIa+RtiGC6MNZhwu/xEaAtYcaFb9bTcfzVJWekJsmRRS98Poj5E6HBpH8e8uM/4cSq2IyY3CBA3WTNVAng/ycp60DMS4Jgx/JMSV/6J2zv2AqRC9RoodITBD33KM2CxFbtzwWsKYSpxnamDtGVEE+8OFDY7XcMxrm53QDIGJM8s6pftuKU6GpgK3wx2ViamwGCS2zwgAGwY8JGjz+tRRf0OW8lYrB1pkcU7kQWMKP6aGYIjVdbjqJ+eKThwEruppdcvCHdxl+4dlPoaKqQpDVhhbR7O2wkH82P8yXqZQoLu+HDaID8PtNq6NpAsbTFsnng+x88S71GKBPy5FOidLF3jI7M3YgZ2n/GcNZUfqkXqxfAw==
    admin-user: AgB+gB+cOZd7tzNjUKQ+1j2dUgpiagIW5CKiylIcp3rv4H9iPXt3f2zPqEJsFa+u3qvVj6dP/ysRDtq28DyFf63HFTdJIcq61qn6VmbMXYrm+ZdSCyO7RcldNdsmNW4xkP5y430LXx99bbPjsm2aN/w+Eygpen/1OBO8TyHXR/37pc+lN+NiNpboDeieSFtUrC1nYPQ4kZ/XZI3pgCmDcCfqEIiNMia72e8YH9d7O1h3fYBBcDFjHvNoGXPW6+x/yolIbHMmgJb8ZcaFoOz5dlKUKuOyuDgsN3FIo07QzLmH0Yz2oPJUQNyIH+7JOEUDo25fuqxKuhDEigQP+C6LZrfnLaaRe6eDgyeC0VatKF5mM3EGracEVv3QtY/WUMwWEfqGJnN7wLl4MweR+GhDbV1yQQ0jjI4FhQAP63j8zvFWftjyN6dEbDBrQI5VVedyEtlPTUg1vHfTCbJF6MhASi3KUNxkxiIEcq5r/R7R1K6qwM+NKeO+j11vXj6m8V1jcLrY9J1sPC+nVxQVym3vzG8xTWLa9ZhXGua3j3Pwsq3tmU/SFl9SFjkjspmealBM9h46aIHq31BWsnQG/cLvLl2gDvDLY30PuCZy+WIXDLUqoIbcChTvNVlSAqZjyHAzi1kQO2kBvUj1IeO9W3Xcuz2hq/MvejLIs8ruuJHtJ4PIalxGIDxW4R5AIe1GETxhdFjlgPCXvQ==
