kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgB/vH5CqL3xPoN44bSq9BITH707okCg4RAVgVcjcWtcwHjKfqPY736ulc/oQbOgmg+kgItMUuBO6amvNg4ejWJmg7+aPpOQXwImpClvP1NlhYVqBg3iZTM109ZUPFIc3LvErypeo6F7xv901iPJ0mC1X508h8Ln4ZeEHKZYNu5HwiU5c+B6e/NsFcDMpGc1jKr2mRc3AYsNxDxSlyVvPLKaXkGh0kuBT0QqYxY6Sn33bd8JMS+cBnm7TLazGlnfWX94i/c9n9MiAn72npuLsqaWQnWuMNs/hkEL4TBGQV8onj1jZiLPnA4iZjlc5j7c6mOA7gzwnbWGcPDm7r/CvuuZGXxC0mtdMVtI7dW8NRlSz2MMHmoVcF5h/yDfOMRrwMigLjFHoPtReo9vwKPxW+TbtJHTG4D9aAAkp4v5sMGsK8/5hW7ycaaUSiVza6LQ0j9A5pEeRWT6k8lvj1GjFXFa5aQh80Rj3gVGkZ+1k26N5GEnCwDjcd7Xy88d23NIeTd8PQXuDG7OAoccCngTYPg1vtzx6D8yYJFRn6GOYYFx1pBeDxeV0pAEyAR2PKq68Knf+S8MRtzDaTe2FJ1QcNLQjbBark20qhZHfSFpjxuSX2FWl3yzfrh3NllR6f91FFAA4TaQRPNpOjfuAwrjiBWC3THcIabJE+Wr450GKN3hE2hrmvlM7MdliWzWKS4527g=
    admin-user: AgC1rZiAq3FY7YSNxMt3UEyC1XTypX+ICzHvbWMtdPck7KQn2A/IR+d8Dwt1jjCB1wcI5ETten37JWHj0RMyUIHvF+12efgLee3DCBM4D25qjIAgXbp4pQb2pc+1SMUrJxNi1ob9+J0TRu4kkn+B+yrt6ulg+k0NRsH80sZU/Y/dILaSa9pcBIGy8ONmxLAM7vf549/uTxjmK8On70DmHlg8NYpQC76BRkHjBivRUYdF9Pm/I7iV/3QdJsK5gVow6c04yMGR8OmzjlDJwC4QRRwUoInFSG5RuBT3DysaMwaq5CIglLycUZVmAa9doj0kfbL2H8FOawPOFUXw7DdBgM3E8sHq74l0VMozIqdEt4uEK7KffFuwshER804Vf5QjNWoyzIMs5vPNgrVp3a0tDxzzUcAb/7QGg7I9+BROIay3IYRmjQEF6WCHiIy30kwewhpyrYbGS4ReJ41lHQS37sGpvl9s+zVXqavNPbjQlyi0KSowxtlQonfgTZTBHqlkMA7z4S32BPxqJuXoJyfZzbIpCf9+LGTSPpektmnXSWStwT/oUZQ/cRRq3tm+UpHoasl6C7HzkXrIgttYnpGJn2TsHi8UkSarVbWp8/6lYQz/S08X8xClTZnPc8NatiJnKjpHRwDtpLe0MMKC96lDdzUOs9ebqpqY0i3ZNjjZA8jgDSOKl+lbKAjvGf8JLLjTE3A=
