kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgCDXlN+1HdYsIo8le2TmK43lt9FALvhprs4R41HC1vq2+fekV8NhKCdXEXS4OdADkHElMNfPb5Y3HQ5qoJIqdRh2I1mhm05DVg76pUf+leqiBUthZp87lyfvS/5opXY1OhxDcsPKjZsaSvRJ9E9TmKA1UCf895ngseY59TVBhcdgAKWthlK9YSojvSnBJm1hf3Q4UKQ2M4XCiUOyRoFsD8h5mldo7g4DqH5OQc5UHtw1hJMhyCZRVlfQo9kUkvoM+dVRV4uzVH5QQO4EvF/zcV6IUnt/P3PCMAr+qcyo7xl9DmCZJdEHtcrLxcMCbw+2vm815Xpr71jJw0Yy+k9AeW1phTXlXo8HRaSgayF4L82bScvWhRGrL5YBvlJX4taHNKwJRCstNkObpyDA2Vw1UR236vxcOK7jj8VTRL+M1/PIC2dgFhkTdqltFBn6y5w3zObi9VcBaFx2tqPc1k2R77flPw779tRsW6QtUj1ZSG+1SBXLpZ3Od98o5011wmIW3l0cYE1Qwu0GV02H0TeKuej68eegNX7vkWyKeXiLRz33I4Btz67I6v7gz32xvEJOOEI98FjbS1tn+LWpEwOF74obp1Nsc8GgRXMs1k2KXo7YjepGpfk9YQpxZbl3hBg44/29b9F3KGpXkIfNdeRjQ6AlzDd6+3Pv55TTGG27Lle4d8DCTsYORAlk1ddILQCzCC+gdqPwg==
    admin-user: AgB0C7uK3XRdIXGV4y8azlhl/Q+Lfaue2hMS8qPordSmfqTbmftU5Bye5n35zMHfuYSAgk++KF5PeI9j6EYNJLEiiAZBJqRGDnBTXkmxmpd1f3CgBOaOI7w44E3hLAsIz4O8Z3P9tdyUK7SVYworoe99LkCXYwRP9JPZbXqELGLLZNCZTC+xRMDoe2XCW3W4S4/ArdrLrrM0tDdPbGAtiMnwBfOrkN+AS1da7zsqlPiKgUCFZGH+C/fhtyCWSGDltDeLGO60SumYkYHDGU59Yjr3RS0OL9S0isS4uvYKsdzIvXscAdPRW6vQlF/4xIZkgceDbBjXpGfeK+Nbg4XRcG0jSQKevRR1iV2Y8VaI7clwvb1Yj4SKyHCI5lto0THesk0dWOnJQ/jlrv5rtmO0dvuKJSCzXi9TuOTHfnjNYaIMbeShuQQVagHN560aTVW6i928db8zjHEJImKlqiUTDVk2CQJCyuqss7m6ZHOOpRUO1V+tWl0aw2efvGU3XwdZUAncInsLFHD6GN3aka0IKkLK+Cp6E7S5S1L9Mhj2AKSBaLCr84OpotJgT5Vd3FGgmwB9XLtKmHNqFBcDCveW5COpEHezO9CVSd+bq/lb0BQuq0RYlJ4G/rVxU8lkje+CWL5BmssSG3cgQNNyI/nVwDCw4C92FuZzS78C1Oppt2pAqnJKfrdOiDGzhqP1oqCVUO+VOL5cuA==
