kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgAgw6PJFGG7GOBRobXJ0n3I1Y6QRagtTtTaUDbnw/RHkXVamFRtLDpjCROvgoxsw2yjC2PZD8wK3uYicEKsJdsql71FedF5UJGdFH/6CjVebwHNME9rZjOxmVBkIy49Gb2WJ5hqKK3jfSveEfYi6lQWfSHrlKKbThOxo6iA8T6VdWnRcwIM0b5xTDz+XfGS2HlEbj3oiWH95ejInaEB3CgiCaE3cyu5DjVZhq6myE6wrx2rnNlh1GDUe1v/xdkyxy18kVTC6hQdMeqUvmWufcrY4qyXLBT9z5eVb+hEVZJpWh6/oXcvNu4YZyhwJ1XYpbqqRvRL/1MLHj82X0cnf+mZeb9vX8UNmbNK3rG6PjB1W7rwI7mjC0/mWfIBjfUjBFvCPdX3MP5xtztMJMuvrObvzTdSVlBZ/qcsmULxFP3SprjUyc/jJrEq7N6b7fp3ZgD+mSnwHqf73tRQGONcAbiKRKOE+891qsTS5tRpX8YXxNZm6Ue3ElUUQ0mCAr8QTcMoBneI+1r8gaAkaqVheX2uB677xygpen+Fc5cleVb2DiU+LbiFF9OUcE/tgX5IBbYtJCkBGav/CxQX9BV8QVvQb3j+Vtg76nMvm4luR4MsN6ifrSxGuWH+sJJKvFBRw5RzGKN18e5AxC8i/xxf6XEA/J7w65bxz0xOdI5fI8XZND5IeGs5xdno8s9qwB116W4Un1T9Rw==
    admin-user: AgBd4zapNXIakvgLK/SHJcwxmTMULLdceQWd4Zxs8RmFpx7rAU5f0ER3AdSh9+ban9bKqJnImIMg3oUIN20TbuwO8x2s1riy1PZOCrsfHktE01HaQ+V9GYhS+lL8pOh7NBV8UdDT9jpt5CEjOOJAkO7v7KJfZWWMkcpkdUXb7V1qayZUtgufkhtuFrhAIneigsubNYy+Od+sp2JSCF++U6bjqKxQ+R1BgB3i1Virt4/VGKlhYLpFe5QFKjW1Giatw9LaQ952CQNrtmx9HpbuLYma9jgTx2utQ62ysfg8cpGuchJNjW9GS9+tnhPojB8tq9gmDgy3OkCoU2HauYQC32Hx/h5S+sABZaG83hCyVM9ic96cyCKNa0TMXWm9/ucow2met2XGIKd+FmS6BjAwUvK2/tCWKLi356nXvK3hvjgIKplAB2TC/sWlouMo0BNTSmlxabi0kd+Q1atZ8GcBErN5g1Cw00X4XheBZVJcz1IN/g3rC/PRDPH5xScHUjezr0ggyP453q/cfDsQb0ad8q4WCFcKhQh4NHyMAgwKRrRAm82uZemqKS0lGSl724MnqDsjHbSeT31bOelLOzTefR70kBKSQajot/2BzXXs+olih8cOtCnCgFC1kidG2qLLz6SUtFsUmE2ulcst8O2/UBBsrMcB+9LJirAuIJ2pPUe6zWWLf4apsBpAuaafLcpchO0Yqu7hwg==
