kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgANDjqMPgCPhL2gspU0wgIKrKi18OVXr2jEwL+HyXetny+8w/IpvKmu/Agj3/7Ji2WXsbr/kW7dMLIPpl1MLEsG5UjMb4K7O8E0aV3Ettg5MoOHXgAt0YXktGxc+yyX9OJxXQW3VIdMR4tSMNESMZbw2tUxizl3vTg81mkUmd8e4TJlfX5U9rCPm7ot7q8JIC2MjguTiIgVsfPjxQ9QOZ+T9PoXkMr+EYY5U0gOJpDeqx7/uj/vks4YWK+C8KIVonimw1IUtMa2bwW01fnwG0giggzJ9SGY2X/yb6X++jO3I/hAOzAadJeOXu58FuupGQWNkzbAcGnjuzlYBn0JP/+GoRWUPxgy/zWcupPKKN8juruTprnl2FvonSKP+Dvoy87KEWVAsrjX5n0tne2vU/HGbTA4L5quPOYcFFXVd1llWch74rZFIZqTE2A4rAVGy6qU6BcBHTd/v/77tne17BezSYTBNU9losfogzSbiFafRsuHINgihAyguQ2p6wueOML6dZjffpik7pNdrC9vp2j3IsSghVG984YcXytOdKn6BKF6WoXnCDVaIhpD2IC96B0MTCIz9ad7Jgq8NBAqzakafE41lKE6+05UHESWG8dI3gS570IOL6NgvMcyEXSShRHbTa5ZgeZw7MjircmmK1sZ9bSYFG6feheaW37sFB3+mh+dMPcBZg7AMKXgrLV3RoNLVg7XBA==
    admin-user: AgCbVhh6+G+ggzAXfQP9gkLlFx/Zt33F6qNBlVDgL+tcTN1yRyObNWqGvfSNm5Uoxnwtm6bg5OyTFvg/tYNAfFhwJvoStZ1+7Hnms/kghTXeWHvxRGDkumVaiv/5DN2xZ2rSTKGcWkNtwnxiUlIZuhXkdqY/9l8aqilPs1B9Yyu3lkQAHvQCKIwCEU8xW9gcpwZhlawYoQABXfqR4J3xJN8nK2KlKbpyEQOklNnS4UgvoVkCCvD+39NivOoYZzhq54sSYlYwCnzMhDWMatIwH+IZI6JLYZj5qApNb4Fgw4IApkGbJBV0JrzzAw7VsfMhyz86X08XuQSYVLGNo54NMyQCUJwxeHeUuZR9Ss4AMb+TX8Tokxhl8EvjyV4W31RCvCLPlYXV+7/0C9vhNctJGbXrp8hcSQ2EjqakQON6yzDReZaGME1751riOs3rp2YRI1RCKnaHAm90S69pkGKtQ9s7CCZZ+D4MqqSQZSHk8/yQ9gESNWybHHB/x0YfxSGBaDKe/rf5TNLh9PPAWx2QBt2gK8E7IipG/ntXWfzmXF09GzCh6ZsC9Az2hHAAagj5BwtkDgpoJj6MKwcpeg52gDKgjPHftnXQmR0EIEvlTr7yMs06G6sOXc0cryWosEgGi3w0A4+9Erd9NxDzXj0+Gi3k4Y4ZGuPQsnw4okbjDFrermePIWCsg4kXVj3o5F+HQFR6vo4Whw==
