kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
  encryptedData:
    admin-password: AgAenF53ToKGipzh+f3ZEiSqR7yEaSUmqgaXgBjCL8yONkt7xlD9zxWuylh6XiQP0jfImQpNH+65Jr0ONjAPbsh0rRhNAFqgXb8Z0aQkvmXJrm7xV+oQ78qrCgZkWu+M2bHW25terXAPVcja1JR8Z1JCgWEoyczX2Oki8A12FnHguc1CE+6XR+ip65KJU/25uXpY0P7tIJc+k5dHZXxIWe62rCpjnr6Fz8/4IOeD1hx87Dmt97iDBL6EicnaN8mvklTFCjpDeY+K0g7dvGxEx1jLC+VdU87Rk5Zq9W42pKxtYeuBj6BsS5T4X7dZcP6ZRRxl6oDEu0SpAzVhs6cTmPuNMR43iAvfNk3g0cbUL27FBZkV+3wDcV+ywTW/6qFeHVt7tFTPI+P4zmvYVSKtEDROlYG0HIZzn74sdm+Cl9UntkGoGkVIOCjGuFD58/z7VhuREnUAjaFG93xkxHqTOtW3+AUaAk0vmgBK4iDLk6jjUQszNDsVaQOFpsKZiGJKUHHuqa2MapnEpX+IkKZaRc7vqLafi3EfMEZ2H+BJciltrlQeRpu2PC99iMaW4x4N/LmPI/ADSidGoRmBPbiehsyeIMkHqEW598kcLqaeZiNZQcdh3QOpHJs4ZSzHOb1dXZncjYUlScxThJXKgI1bIiEXNJShq8dJl0jHWhTxl/U25DQVLMQpZxA95oq/pkC5izYACTWYwQ==
    admin-user: AgAr3gxq0gWv6RCGwAhSmFLr0NQfcQxSal8NsMZX++Zs41PMN8h50xk4sGojHdqbdM07BFNbQilYwOawi3beCDKy82L/7UNwql5ZhjmW6eKBsAkP0zQhEVlNGvcSb+bhvMYvKPi144kbFyMqxzsjo9EI9xCdR17WxHHQTPpRFoOGl5MkM/SeyJl1/caj0EVaffb+YDT2yYUAVh7grq4fPTEoccf8JUFkwtxZvHnjqzTWNjp9eikQoGEdAaLxzC4MGSFsMud6CrTNKpL5Q9G+uWbWrvn0wio8JZR0+WUma5AJt0sfYeArGfleblJiomBfS0bsB2hMSi39XEwElUmnrayNcjGet1R2Yff/n1W8/o7SihkgZbgt+eQyRJYhghuPsdgQ5oeoD9sR3k1T0vU7i/Cd58Yd++8nXABBfCJ2ksfvfiduA3hdbmrj4MrEEmTQz99C5XKbDWePknG96MppUX0rYgROKeCMV3VsYgFdXgY+qCb66YLSmjjtzQOy0pRvv6lsvWX3hIiwD2Jbb3r6IYraRjzzuhu27cAHWLPvcU+7I8dGZ0qwngFpwdhZyiP03yXv/CGL9TzjZqiFKjCHyQb1xchDzU/zbqwawyFRn//XICTWh1zdgMky6BX9BuUu7rUpAQ/iu/GkM3sMyBasgtqjM0MgsEGd+z+9/9Vj71JiPWPAvprBVcykEHazThl7OEOWcz7nJg==
